name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - flask
  - pytest
  - flake8
  - pip:
    - python-telegram-bot
    - bitcoin
    - asyncio
    - socket
